services:
  influxdb-pfsense:
    image: influxdb:1.8
    container_name: influxdb-pfsense
    hostname: influxdb_pfsense
    mem_limit: 4gb
    restart: always
    user: "1000"
    ports:
      - "2003:2003"
      - "8086:8086"
    volumes:
      - /home/portainer/homelab/influxdb-pfsense/data:/var/lib/influxdb
    env_file:
      - stack.env
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
    networks:
      - net

networks:
  net:
    external:
      name: proxynet
