services:
  navidrome:
    container_name: navidrome
    hostname: navidrome
    image: deluan/navidrome:latest
    user: 1000:1000
    ports:
      - "4533:4533"
    env_file:
      - stack.env
    volumes:
      - /home/portainer/homelab/navidrome/data:/data
      - /home/portainer/shared/music:/music:ro
    restart: unless-stopped
