services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - 3030:3000
    user: "1000"
    volumes:
      - /home/portainer/homelab/grafana/data:/var/lib/grafana
      - /home/portainer/homelab/grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - /home/portainer/homelab/grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - net

networks:
  net:
    external:
      name: proxynet
