services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - /home/portainer/homelab/homepage/config:/app/config
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - net

networks:
  net:
    external:
      name: proxynet

