services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - "/home/portainer/homelab/homepage/config:/app/config"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - stack.env
    restart: unless-stopped
