services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    ports:
      - "8081:8081"
    volumes:
      - /home/portainer/shared/videos:/downloads
    restart: unless-stopped
