---
- Management:
  - Proxmox VE:
      description: Open-source virtualization and LXC platform
      href: https://pve.calegaro.net
      icon: proxmox.png
      widget:
        type: proxmox
        url: https://pve.calegaro.net
        username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
        password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"

  - Portainer:
      description: Universal container management platform
      href: https://portainer.calegaro.net
      icon: portainer.png
      container: portainer
      server: local
      widget:
        type: portainer
        url: https://portainer.calegaro.net
        env: 2
        key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"

- Network:
  - pfSense:
      description: Free and open-source firewall and router solution
      icon: pfsense.png
      href: https://pfsense.calegaro.net
      widget:
        proxy: true
        type: pfsense
        url: https://pfsense.calegaro.net
        username: "{{HOMEPAGE_VAR_PFSENSE_USERNAME}}"
        password: "{{HOMEPAGE_VAR_PFSENSE_PASSWORD}}"
        wan: pppoe0

  - Nginx Proxy Manager:
      description:
      icon: nginx-proxy-manager
      href: http://proxy.calegaro.net:81
      container: proxy
      server: proxy
      widget:
        proxy: true
        type: npm
        url: http://proxy.calegaro.net:81
        username: "{{HOMEPAGE_VAR_NPM_USERNAME}}"
        password: "{{HOMEPAGE_VAR_NPM_PASSWORD}}"

  - Speedtest Tracker:
      description: Internet speed tracking with Ookla's speedtest-cli
      href: https://speedtest.calegaro.net
      icon: speedtest-tracker.png
      container: speedtest-tracker
      server: local
      widget:
        type: speedtest
        url: https://speedtest.calegaro.net

- Monitoring:
  - Grafana:
      description:
      href: https://grafana.calegaro.net
      icon: grafana.png
      container: grafana
      server: local
      widget:
        type: grafana
        url: https://grafana.calegaro.net
        username: "{{HOMEPAGE_VAR_GRAFANA_USERNAME}}"
        password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"

- Media:
  - Navidrome:
      description: Your Personal Streaming Service
      href: https://navidrome.calegaro.net
      icon: navidrome.png
      container: navidrome
      server: local
      widget:
        type: navidrome
        url: https://navidrome.calegaro.net
        user: "{{HOMEPAGE_VAR_NAVIDROME_USERNAME}}"
        token: "{{HOMEPAGE_VAR_NAVIDROME_TOKEN}}"
        salt: "{{HOMEPAGE_VAR_NAVIDROME_SALT}}"

  - Metube:
      description: Web UI for yt-dlp
      href: https://metube.calegaro.net
      icon: metube.png
      container: metube
      server: local
