---
- Management:
  - Proxmox VE:
      description: Open-source virtualization and LXC platform
      href: https://pve.calegaro.net
      icon: proxmox.png
      ping: https://pve.calegaro.net
      siteMonitor: https://pve.calegaro.net
      widget:
        type: proxmox
        url: https://pve.calegaro.net
        username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
        password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"

  - Portainer (main):
      description: Universal container management platform
      href: https://portainer.calegaro.net
      icon: portainer.png
      container: portainer
      server: local
      ping: https://portainer.calegaro.net
      siteMonitor: https://portainer.calegaro.net
      widget:
        type: portainer
        url: https://portainer.calegaro.net
        env: 2
        key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"

  - Portainer (servarr):
      description: Universal container management platform
      href: https://portainer-servarr.calegaro.net
      icon: portainer.png
      container: portainer
      server: servarr
      ping: https://portainer-servarr.calegaro.net
      siteMonitor: https://portainer-servarr.calegaro.net
      widget:
        type: portainer
        url: https://portainer-servarr.calegaro.net
        env: 2
        key: "{{HOMEPAGE_VAR_PORTAINER_SERVARR_API_KEY}}"

- Network:
  - pfSense:
      description: Free and open-source firewall and router solution
      icon: pfsense.png
      href: https://pfsense.calegaro.net
      ping: https://pfsense.calegaro.net
      siteMonitor: https://pfsense.calegaro.net
      widget:
        proxy: true
        type: pfsense
        url: https://pfsense.calegaro.net
        username: "{{HOMEPAGE_VAR_PFSENSE_USERNAME}}"
        password: "{{HOMEPAGE_VAR_PFSENSE_PASSWORD}}"
        wan: pppoe0

  - Nginx Proxy Manager:
      description: Expose web services on your network with SSL
      icon: nginx-proxy-manager
      href: https://npm.calegaro.net
      container: nginx-proxy-manager
      server: proxy
      ping: https://npm.calegaro.net
      siteMonitor: https://npm.calegaro.net
      widget:
        proxy: true
        type: npm
        url: https://npm.calegaro.net
        username: "{{HOMEPAGE_VAR_NPM_USERNAME}}"
        password: "{{HOMEPAGE_VAR_NPM_PASSWORD}}"

  - Speedtest Tracker:
      description: Internet speed tracking with Ookla's speedtest-cli
      href: https://speedtest2.calegaro.net
      icon: speedtest-tracker.png
      container: speedtest-tracker-2
      server: local
      ping: https://speedtest2.calegaro.net
      siteMonitor: https://speedtest2.calegaro.net
      widget:
        type: speedtest
        url: https://speedtest2.calegaro.net

- Monitoring:
  - Grafana:
      href: https://grafana.calegaro.net
      icon: grafana.png
      container: grafana
      server: local
      ping: https://grafana.calegaro.net
      siteMonitor: https://grafana.calegaro.net
      widget:
        type: grafana
        url: https://grafana.calegaro.net
        username: "{{HOMEPAGE_VAR_GRAFANA_USERNAME}}"
        password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"

  - Netdata:
      description: Real-time data collection, aggregation and visualization
      href: https://netdata-pve.calegaro.net
      icon: netdata
      ping: https://netdata-pve.calegaro.net
      siteMonitor: https://netdata-pve.calegaro.net
      widget:
        type: netdata
        url: https://netdata-pve.calegaro.net

  - InfluxDB v2:
      description: Time series database
      href: https://influxdb-v2.calegaro.net
      icon: influxdb
      container: influxdb-v2
      server: local
      ping: https://influxdb-v2.calegaro.net
      siteMonitor: https://influxdb-v2.calegaro.net

- Media:
  - Navidrome:
      description: Your Personal Streaming Service
      href: https://navidrome.calegaro.net
      icon: navidrome.png
      container: navidrome
      server: servarr
      ping: https://navidrome.calegaro.net
      siteMonitor: https://navidrome.calegaro.net
      widget:
        type: navidrome
        url: https://navidrome.calegaro.net
        user: "{{HOMEPAGE_VAR_NAVIDROME_USERNAME}}"
        token: "{{HOMEPAGE_VAR_NAVIDROME_TOKEN}}"
        salt: "{{HOMEPAGE_VAR_NAVIDROME_SALT}}"

  - Volumio:
      description: Network music player
      href: http://pi4.home.lan
      icon: volumio.png
      ping: http://pi4.home.lan
      siteMonitor: http://pi4.home.lan

  - Jellyfin:
      description: The Free Software Media System
      href: https://jellyfin.calegaro.net
      icon: jellyfin.png
      ping: https://jellyfin.calegaro.net
      siteMonitor: https://jellyfin.calegaro.net
      widget:
        type: jellyfin
        url: https://jellyfin.calegaro.net
        key: cc2b3f03157742a5a38abce3c1cf6028
        enableBlocks: true
        enableNowPlaying: false
        enableUser: true
        expandOneStreamToTwoRows: false

- Arr:
  - Sonarr:
      description: See all your upcoming episodes in one convenient location
      href: https://sonarr.calegaro.net
      icon: sonarr.png
      container: sonarr
      server: servarr
      ping: https://sonarr.calegaro.net
      siteMonitor: https://sonarr.calegaro.net
      widget:
        type: sonarr
        url: https://sonarr.calegaro.net
        key: "{{HOMEPAGE_VAR_SONARR_TOKEN}}"

  - Radarr:
      description: See all your upcoming movies in one convenient location
      href: https://radarr.calegaro.net
      icon: radarr.png
      container: radarr
      server: servarr
      ping: https://radarr.calegaro.net
      siteMonitor: https://radarr.calegaro.net
      widget:
        type: radarr
        url: https://radarr.calegaro.net
        key: "{{HOMEPAGE_VAR_RADARR_TOKEN}}"

  - Lidarr:
      description: Music collection manager for Usenet and BitTorrent users
      href: https://lidarr.calegaro.net
      icon: lidarr.png
      container: lidarr
      server: servarr
      ping: https://lidarr.calegaro.net
      siteMonitor: https://lidarr.calegaro.net
      widget:
        type: lidarr
        url: https://lidarr.calegaro.net
        key: "{{HOMEPAGE_VAR_LIDARR_TOKEN}}"

  - Prowlarr:
      description: The Ultimate Indexer Manager
      href: https://prowlarr.calegaro.net
      icon: prowlarr.png
      container: prowlarr
      server: servarr
      ping: https://prowlarr.calegaro.net
      siteMonitor: https://prowlarr.calegaro.net
      widget:
        type: prowlarr
        url: https://prowlarr.calegaro.net
        key: "{{HOMEPAGE_VAR_PROWLARR_TOKEN}}"

- Download:
  - qBittorrent:
      description: Free and reliable P2P Bittorrent client
      href: https://qbittorrent.calegaro.net
      icon: qbittorrent.png
      container: qbittorrent
      server: servarr
      ping: https://qbittorrent.calegaro.net
      siteMonitor: https://qbittorrent.calegaro.net
      widget:
        type: qbittorrent
        url: https://qbittorrent.calegaro.net
        username: "{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}"
        password: "{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}"
        enableLeechProgress: true

  - NZBGet:
      description: Efficient usenet downloader
      href: https://nzbget.calegaro.net
      icon: nzbget.svg
      container: nzbget
      server: servarr
      ping: https://nzbget.calegaro.net
      siteMonitor: https://nzbget.calegaro.net
      widget:
        type: nzbget
        url: https://nzbget.calegaro.net
        username: "{{HOMEPAGE_VAR_NZBGET_USERNAME}}"
        password: "{{HOMEPAGE_VAR_NZBGET_PASSWORD}}"

  - Metube:
      description: Web UI for yt-dlp
      href: https://metube.calegaro.net
      icon: metube.png
      container: metube
      server: local
      ping: https://metube.calegaro.net
      siteMonitor: https://metube.calegaro.net

- Gaming:
  - Crafty Controller:
      description: A web-based GUI for Minecraft server administration
      href: https://crafty.calegaro.net
      icon: crafty-controller.png
      container: crafty-controller
      server: crafty
      ping: https://crafty.calegaro.net
      siteMonitor: https://crafty.calegaro.net
